### ISSUE TITLE
Implement a way to load options from a generic config files with other data

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/OptParseValidator#19]
Currently the CLI options, when the ConfigFilesLoaderMerger is used, are loaded and parsed from files which can only contain the options.

A scanner might want to have a ```scan.yml``` containing various config values, including the CLI options. So in the current implementation, two files need to be created (scan.yml and another one with the cli options) rather than just one.

Example of ```scan.yml```

```yml
some_config: 'some value'
another_config:
  key: 'something'
cli_options:
  verbose: true
```

This will need the constructor to be reworked, and add a hash as an argument, as opposed to fixed arguments to be able to pass config_files options like the ```return_key``` and ```yaml_arguments```
